"""
模型导出脚本
将训练好的 Keras .h5 模型转换为 C 头文件 (cnn_weights.h)

用法：
  python export_model.py --model fatigue_model.h5 --output ../E18_usb_cdc_demo/code/cnn_weights.h
"""
import numpy as np
import argparse
import os

def format_array(name, arr, indent=4):
    """将 numpy 数组格式化为 C const float 数组"""
    flat = arr.flatten()
    lines = []
    line = ""
    for i, v in enumerate(flat):
        if line:
            line += ", "
        line += f"{v:.8f}f"
        if len(line) > 70 or i == len(flat) - 1:
            lines.append(" " * indent + line)
            line = ""

    shape_str = "".join(f"[{d}]" for d in arr.shape)
    header = f"const float {name}{shape_str} = {{"
    footer = "};"

    result = header + "\n"
    result += ",\n".join(lines)
    result += "\n" + footer
    return result

def export_model(model_path, output_path):
    """导出模型权重到 C 头文件"""
    # 延迟导入 tensorflow
    from tensorflow import keras

    model = keras.models.load_model(model_path)
    print(f"Model loaded: {model_path}")
    print(f"Layers: {len(model.layers)}")

    with open(output_path, "w") as f:
        f.write("/* Auto-generated CNN weights - DO NOT EDIT */\n")
        f.write("/* Generated by export_model.py */\n")
        f.write("#ifndef _CNN_WEIGHTS_H_\n")
        f.write("#define _CNN_WEIGHTS_H_\n\n")
        f.write("#include <stdint.h>\n\n")

        layer_idx = 0
        for layer in model.layers:
            weights = layer.get_weights()
            if not weights:
                continue

            w, b = weights[0], weights[1]
            print(f"  Layer {layer.name}: weights {w.shape}, bias {b.shape}")

            # 权重
            f.write(f"/* {layer.name} weights */\n")
            f.write(format_array(f"cnn_w{layer_idx}", w))
            f.write("\n\n")

            # 偏置
            f.write(f"/* {layer.name} bias */\n")
            f.write(format_array(f"cnn_b{layer_idx}", b))
            f.write("\n\n")

            layer_idx += 1

        # 写入模型结构信息
        f.write("/* Model structure defines */\n")
        f.write(f"#define CNN_NUM_LAYERS {layer_idx}\n\n")

        # 解析各层维度并写入
        layer_idx = 0
        for layer in model.layers:
            weights = layer.get_weights()
            if not weights:
                continue
            w = weights[0]
            if len(w.shape) == 4:  # Conv2D: [kh, kw, cin, cout]
                kh, kw, cin, cout = w.shape
                f.write(f"#define CNN_L{layer_idx}_KH {kh}\n")
                f.write(f"#define CNN_L{layer_idx}_KW {kw}\n")
                f.write(f"#define CNN_L{layer_idx}_CIN {cin}\n")
                f.write(f"#define CNN_L{layer_idx}_COUT {cout}\n\n")
            elif len(w.shape) == 2:  # Dense: [in, out]
                din, dout = w.shape
                f.write(f"#define CNN_L{layer_idx}_DIN {din}\n")
                f.write(f"#define CNN_L{layer_idx}_DOUT {dout}\n\n")
            layer_idx += 1

        f.write("#endif /* _CNN_WEIGHTS_H_ */\n")

    print(f"\nWeights exported to {output_path}")
    print(f"File size: {os.path.getsize(output_path)} bytes")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export Keras model to C header")
    parser.add_argument("--model", default="fatigue_model.h5", help="Input .h5 model")
    parser.add_argument("--output", default="../E18_usb_cdc_demo/code/cnn_weights.h",
                        help="Output C header file")
    args = parser.parse_args()

    export_model(args.model, args.output)
